### ISSUE TITLE
Issues with XboxController through advantagekit

### ISSUE THREAD

**Issue by daisystudent341** [Mechanical-Advantage/AdvantageKit#30] opened 2023-01-14 14:14 UTC
When using an XboxController class through advantagekit, we experience a Joystick unplugged error, where the program warns us that it is not registering the buttons on the controller. When using an XboxController through Wpilib instead, it works fine.

This did work on the Beta, so we're not sure what the issue could be.

We are using a Logitech Gamepad F310.

**Comment by jwbonner** [comment] 2023-01-14 14:23
Could you check that your `Robot` class inherits from `LoggedRobot` and not `TimedRobot`?

**Comment by macfraser** [comment] 2023-01-26 02:25
I have seen the same with the some base code we started from the command based skeleton. Running a Rio2

**Comment by jwbonner** [comment] 2023-01-26 02:35
@macfraser Could you confirm that the controller appears correctly in the Driver Station on port 0? If that looks good then it would be helpful if you could send the AdvantageKit log file.

**Comment by lidor51** [comment] 2023-10-19 11:17
Any update on that? Since it's seems like a critical issue.

**Comment by jwbonner** [comment] 2023-10-19 15:38
@daisystudent341 @macfraser If you could confirm whether you fixed this that would be useful. I haven't seen any confirmed report of this issue in a recent version of AdvantageKit, though. The current version enforces that the robot class must inherit from LoggedRobot, which was a common tripping point. It's unfortunately easy to mix up joystick ports too, but that's unrelated to AdvantageKit.

I would expect that if other users experienced this problem, we would have additional reports. We'll look into it if we hear anything, but otherwise I'll plan to close this issue in a couple weeks.

**Closed** 2023-10-30 15:59 UTC
